### ISSUE TITLE
students--> adding new students

### ISSUE THREAD

**Issue by prem-raj461** [thuloims/thuloims#9]
--> birthdate take future date also, phone no take input of any length
-->father phone can take string value also
--> email field take invalid email also
--> citizen ship no take string value also
--> passport take invalid value also
--> join date take future date also

**Comment by thulotechnology** [comment]
Birthday Issue is Solved.
  Father Phone Validation is done.
  Citizenship/ Passport may takes value like - so it is okay
  Join Date Issue is Solved.
